name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - run: npm run build
        env:
          CI: true

      # 👇 Explicitly add upload-artifact@v3 to avoid the missing info error
      - name: Preload upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: preload
          path: ./dummy.txt
        continue-on-error: true

      - uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - id: deployment
        uses: actions/deploy-pages@v2
